import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { ChannelProvider } from "@/providers/channel-provider";
import { getActiveChannel } from "@/lib/vendure/actions";
import { getCurrencyCode, getLanguageCode } from "@/lib/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [currencyCode, languageCode] = await Promise.all([
    getCurrencyCode(),
    getLanguageCode(),
  ]);

  const channel = await getActiveChannel();

  if (!channel) {
    throw new Error('Failed to load channel data');
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ChannelProvider
          channel={channel}
          initialCurrencyCode={currencyCode || channel.defaultCurrencyCode}
          initialLanguageCode={languageCode || channel.defaultLanguageCode}
        >
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ChannelProvider>
      </body>
    </html>
  );
}
